[PLAT-26620] Log multiple instances of devbox to sentry
databricks/devbox pull request #30
Opened 2021-01-29 19:17 UTC by gabrielrussoc

Let's log an entry to sentry to get a better understanding of how common this error is.

https://sentry.dev.databricks.com/sentry/devbox/issues/93360/events/

2021-01-29 19:18 UTC, gabrielrussoc commented on devbox/common/src/Util.scala
>      io.sentry.Sentry.getContext().addTag("whoami", System.getProperty("user.name"))
I tried to reuse this with the `Event` but for some reason it didn't work. So I ended up adding it on the `EventBuilder` as well.

2021-02-01 10:23 UTC, iuliand-db requested changes

2021-02-01 10:23 UTC, iuliand-db commented on launcher/src/Instance.scala
> +              .withTag("whoami", System.getProperty("user.name"))
Let's add some details about the instances themselves, perhaps creation date and state? We might be able to guess some patterns about the conditions under which we get to this state.

2021-02-01 14:10 UTC, gabrielrussoc commented
Added info about the instances, example:
https://sentry.dev.databricks.com/sentry/devbox/issues/93360/events/3491888/

2021-02-01 16:24 UTC, iuliand-db approved these changes

2021-02-01 16:28 UTC, merged